compute_environment: LOCAL_MACHINE
main_process_ip: "127.0.0.1"
main_process_port: 8779
debug: false
distributed_type: FSDP
enable_cpu_affinity: false
fsdp_config:
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_backward_prefetch: BACKWARD_PRE
  fsdp_cpu_ram_efficient_loading: true
  min_num_params: 10000000  # 1e7
  fsdp_forward_prefetch: true
  fsdp_offload_params: false
  fsdp_sharding_strategy: FULL_SHARD
  fsdp_state_dict_type: SHARDED_STATE_DICT
  fsdp_sync_module_states: true
  fsdp_use_orig_params: true
machine_rank: 0
main_training_function: train
mixed_precision: bf16
num_machines: 1
num_processes: 4
rdzv_backend: static
same_network: true